###
# Authenticate User
###
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "contato@lucianomeireles.io",
  "password": "password123"
}

###
GET {{baseURL}}/auth/loggedUser
Authorization: Bearer {{token}}

###
DELETE {{baseURL}}/logout
Authorization: Bearer {{token}}