###
# Books
###

GET {{baseURL}}/books
Authorization: Bearer {{token}}

###

POST {{baseURL}}/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "author": "Luciano Meireles",
  "title": "Luciano's Book",
  "description": "my book description"
}

###

GET {{baseURL}}/books/645d38dbd768c6590d7aace1
Authorization: Bearer {{token}}

###

PUT {{baseURL}}/books/645d38dbd768c6590d7aace1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "author": "Luciano Meireles",
  "title": "Luciano's Book 2",
  "description": "my book description"
}

###

DELETE {{baseURL}}/books/645d36b44b0cea55b72becce
Authorization: Bearer {{token}}
