###
# Users
###

GET {{baseURL}}/users
Authorization: Bearer {{token}}

###

POST {{baseURL}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New User 2",
  "email": "newuser2@email.com",
  "password": "mypassword2"
}

###

GET {{baseURL}}/users/6489d7f457fcbe287b9d2758
Authorization: Bearer {{token}}

###

PUT {{baseURL}}/users/6489d7f457fcbe287b9d2758
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New User",
  "email": "newuser@email.com",
  "password": "mypassword2"
}

###

DELETE {{baseURL}}/users/6489d7f457fcbe287b9d2758
Authorization: Bearer {{token}}
